### ISSUE TITLE
Why only use 1 iteration in sinkhorn algorithm

### ISSUE THREAD

**Issue by Yingdong-Hu** [csyanbin/SCOT#3]
https://github.com/csyanbin/SCOT/blob/0f5860897c45e1ad101f3ab9c7f452ac34875420/model/rhm_map.py#L11

Hello, thanks for your great work.

You wrote in your paper that you set max iteration in sinkhorn algorithm to 50. 
But why the code only use 1 iteration ?

**Comment by csyanbin** [comment]
Hi, thanks for your interest in our paper. 

Originally, we set max_iteration to a high value, e.g. 50 in the paper. 
However, since Sinkhorn algorithm is fast to converge, it is sufficient to set the iteration to a small value (e.g 1 or 5) according to different applications. 

In general, our algorithm is not sensitive to the max_iteration parameter.
